---
  - name: Set Jenkin's security flag to false
    shell: sed -i 's/useSecurity>true/useSecurity>false/g' /var/lib/jenkins/config.xml

  - name: Ensure Jenkins is started and runs on startup.
    service: name=jenkins state=restarted enabled=yes

  - name: Wait for Jenkins to start up before proceeding.
    shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
    register: result
    until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
    retries: "{{ jenkins_connection_retries }}"
    delay: "{{ jenkins_connection_delay }}"
    changed_when: false
    check_mode: no
    
  - name: Create a user for Ansible on the new Jenkins CLI server
    shell: echo 'hpsr=new hudson.security.HudsonPrivateSecurityRealm(false); hpsr.createAccount("ansible2", "@bc12E")' | java -jar /opt/jenkins-cli.jar -s http://localhost:8080 groovy =
    
  - name: Set Jenkin's security flag to true
    shell: sed -i 's/useSecurity>false/useSecurity>true/g' /var/lib/jenkins/config.xml

  - name: Restart Jenkin's to enforce new security settings
    service: name=jenkins state=restarted enabled=yes
